name: winning-poker-hand-rank pull request test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run winning-poker-hand-rank tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: |
          npm ci
          npm run lint
          npm run build
        env:
          CI: true
